### ISSUE TITLE
Fix babel vulnerability

### ISSUE THREAD

**Issue by vprince1** [aws-solutions-library-samples/guidance-for-product-substitutions-on-aws#5]
A new "critical severity" vulnerability was identified recently for `@babel/traverse`. More details are in https://github.com/advisories/GHSA-67hx-6x53-jw92. Since your repository is using this package, kindly fix it at the earliest.

**Comment by vprince1** [comment]
I still see references to older version

![image](https://github.com/aws-solutions-library-samples/guidance-for-product-substitutions-on-aws/assets/11996632/9f5e785e-fa1a-4386-b0b4-b4e8022d1c93)

**Comment by asenousy** [comment]
done

**Comment by vprince1** [comment]
I still see the same old versions. Versions above 7.23.2 should be used.

![image](https://github.com/aws-solutions-library-samples/guidance-for-product-substitutions-on-aws/assets/11996632/784cea38-efd6-4e0a-ba36-7dc94a17cc7e)

**Comment by asenousy** [comment]
done, sorry about that
